version: '3.8'

services:
  backend:
    build:
      context: ./backend # Исправляем путь на актуальный
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env # Указываем точный путь к .env
    depends_on:
      db:
        condition: service_healthy  # Ждём, пока база данных будет готова
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    env_file:
    - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # Добавляем проверку состояния
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  portainer_data:

networks:
  app-network:
    driver: bridge
